### ISSUE TITLE
Generic error when trying to refund more than the captured amount

### ISSUE THREAD

**Issue by LarsBoThomsen** [paylike/plugin-prestashop#2]
It says "An error occured".

Tried here to refund 200 on a transaction of 34:

http://paylike.byethost33.com/presta/ps/index.php?controller=AdminOrders&id_order=22&vieworder&token=f6d84171e610a60ebcc0b2c77e659f1d

**Comment by farobarcha** [comment]
If refund request fails it will display the error message "An error occurred". I have changed the error message to "Refund Request Failed". Is this ok?

**Comment by farobarcha** [comment]
Added better error handling. Please check again

**Comment by ionutcalara** [comment]
This is stale, closing, for now, feel free to reopen.
