### ISSUE TITLE
Possible issue with debug logging

### ISSUE THREAD

**Issue by LarsBoThomsen** [paylike/plugin-prestashop#3]
A merchant has successfully implemented the plugin. Though, he wrote me the following:

Thank you, implementation went smooth. Had to comment out the following lines though to get it working, just so you know.

In controllers/front/paymentreturn.php

```
if (self::DEBUG_MODE)
PrestaShopLogger::addLog('PaymentModule::validateOrder - Message is about to be added', 1, null, 'Cart', (int)$cart->id, true);
```

**Comment by tjconcept** [comment]
It sounds like the user is running their website in debug-mode, which I guess is not best practice for Prestashop.

Could you dig deeper into the actual error message received _before_ commenting the lines? Could be that their logging system is badly configured.

**Comment by tjconcept** [comment]
This logging has now been removed in the source code, but I'm still not convinced it was actually a bug in the first place. Did the merchant ever reply about whether the site was running in debug-mode?

**Comment by ionutcalara** [comment]
This is stale, closing, for now, feel free to reopen.
